// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: explore/explore-service.proto

package explore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExploreAPI_ListLikedYou_FullMethodName    = "/explore.ExploreAPI/ListLikedYou"
	ExploreAPI_ListNewLikedYou_FullMethodName = "/explore.ExploreAPI/ListNewLikedYou"
	ExploreAPI_CountLikedYou_FullMethodName   = "/explore.ExploreAPI/CountLikedYou"
	ExploreAPI_PutDecision_FullMethodName     = "/explore.ExploreAPI/PutDecision"
)

// ExploreAPIClient is the client API for ExploreAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExploreAPIClient interface {
	ListLikedYou(ctx context.Context, in *ListLikedYouRequest, opts ...grpc.CallOption) (*ListLikedYouResponse, error)
	ListNewLikedYou(ctx context.Context, in *ListLikedYouRequest, opts ...grpc.CallOption) (*ListLikedYouResponse, error)
	CountLikedYou(ctx context.Context, in *CountLikedYouRequest, opts ...grpc.CallOption) (*CountLikedYouResponse, error)
	PutDecision(ctx context.Context, in *PutDecisionRequest, opts ...grpc.CallOption) (*PutDecisionResponse, error)
}

type exploreAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewExploreAPIClient(cc grpc.ClientConnInterface) ExploreAPIClient {
	return &exploreAPIClient{cc}
}

func (c *exploreAPIClient) ListLikedYou(ctx context.Context, in *ListLikedYouRequest, opts ...grpc.CallOption) (*ListLikedYouResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLikedYouResponse)
	err := c.cc.Invoke(ctx, ExploreAPI_ListLikedYou_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploreAPIClient) ListNewLikedYou(ctx context.Context, in *ListLikedYouRequest, opts ...grpc.CallOption) (*ListLikedYouResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLikedYouResponse)
	err := c.cc.Invoke(ctx, ExploreAPI_ListNewLikedYou_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploreAPIClient) CountLikedYou(ctx context.Context, in *CountLikedYouRequest, opts ...grpc.CallOption) (*CountLikedYouResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountLikedYouResponse)
	err := c.cc.Invoke(ctx, ExploreAPI_CountLikedYou_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploreAPIClient) PutDecision(ctx context.Context, in *PutDecisionRequest, opts ...grpc.CallOption) (*PutDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutDecisionResponse)
	err := c.cc.Invoke(ctx, ExploreAPI_PutDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExploreAPIServer is the server API for ExploreAPI service.
// All implementations must embed UnimplementedExploreAPIServer
// for forward compatibility.
type ExploreAPIServer interface {
	ListLikedYou(context.Context, *ListLikedYouRequest) (*ListLikedYouResponse, error)
	ListNewLikedYou(context.Context, *ListLikedYouRequest) (*ListLikedYouResponse, error)
	CountLikedYou(context.Context, *CountLikedYouRequest) (*CountLikedYouResponse, error)
	PutDecision(context.Context, *PutDecisionRequest) (*PutDecisionResponse, error)
	mustEmbedUnimplementedExploreAPIServer()
}

// UnimplementedExploreAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExploreAPIServer struct{}

func (UnimplementedExploreAPIServer) ListLikedYou(context.Context, *ListLikedYouRequest) (*ListLikedYouResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLikedYou not implemented")
}
func (UnimplementedExploreAPIServer) ListNewLikedYou(context.Context, *ListLikedYouRequest) (*ListLikedYouResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNewLikedYou not implemented")
}
func (UnimplementedExploreAPIServer) CountLikedYou(context.Context, *CountLikedYouRequest) (*CountLikedYouResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountLikedYou not implemented")
}
func (UnimplementedExploreAPIServer) PutDecision(context.Context, *PutDecisionRequest) (*PutDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutDecision not implemented")
}
func (UnimplementedExploreAPIServer) mustEmbedUnimplementedExploreAPIServer() {}
func (UnimplementedExploreAPIServer) testEmbeddedByValue()                    {}

// UnsafeExploreAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExploreAPIServer will
// result in compilation errors.
type UnsafeExploreAPIServer interface {
	mustEmbedUnimplementedExploreAPIServer()
}

func RegisterExploreAPIServer(s grpc.ServiceRegistrar, srv ExploreAPIServer) {
	// If the following call pancis, it indicates UnimplementedExploreAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExploreAPI_ServiceDesc, srv)
}

func _ExploreAPI_ListLikedYou_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLikedYouRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploreAPIServer).ListLikedYou(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExploreAPI_ListLikedYou_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploreAPIServer).ListLikedYou(ctx, req.(*ListLikedYouRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploreAPI_ListNewLikedYou_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLikedYouRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploreAPIServer).ListNewLikedYou(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExploreAPI_ListNewLikedYou_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploreAPIServer).ListNewLikedYou(ctx, req.(*ListLikedYouRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploreAPI_CountLikedYou_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountLikedYouRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploreAPIServer).CountLikedYou(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExploreAPI_CountLikedYou_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploreAPIServer).CountLikedYou(ctx, req.(*CountLikedYouRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploreAPI_PutDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploreAPIServer).PutDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExploreAPI_PutDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploreAPIServer).PutDecision(ctx, req.(*PutDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExploreAPI_ServiceDesc is the grpc.ServiceDesc for ExploreAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExploreAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "explore.ExploreAPI",
	HandlerType: (*ExploreAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLikedYou",
			Handler:    _ExploreAPI_ListLikedYou_Handler,
		},
		{
			MethodName: "ListNewLikedYou",
			Handler:    _ExploreAPI_ListNewLikedYou_Handler,
		},
		{
			MethodName: "CountLikedYou",
			Handler:    _ExploreAPI_CountLikedYou_Handler,
		},
		{
			MethodName: "PutDecision",
			Handler:    _ExploreAPI_PutDecision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "explore/explore-service.proto",
}
